name: manager_provider
description: A provider wrapper and set of the widgets to use with manager package.
version: 0.1.9

repository: https://github.com/mcfugger/managerV2/tree/master/packages/manager_provider

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  manager: ^0.1.9
  meta: ^1.7.0
  provider: ^6.0.3

dev_dependencies:
  dart_code_metrics: ^4.17.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
