name: manager
description: A starting point for Dart libraries or applications.
version: 0.0.1

repository: https://github.com/mcfugger/managerV2

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  meta: ^1.7.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
