name: manager
description: A dart package for predictable synchronous and asynchronous state management.
version: 0.3.1

repository: https://github.com/mcfugger/managerV2/tree/master/packages/manager

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  async: ^2.8.2
  meta: ^1.7.0
  rxdart: ^0.27.5

dev_dependencies:
  dart_code_metrics: ^4.17.1
  lints: ^2.0.0
  test: ^1.16.0
