name: manager
description: A new state management architecture pattern.
version: 0.0.6

repository: https://github.com/mcfugger/managerV2/tree/master/packages/manager

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  meta: ^1.7.0
  async: ^2.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
